version: '3.5'
services:
  app:
    container_name: blogging-platform-app
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    ports:
      - '8000:8000'
    volumes:
      - ${PWD}:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5050:80'
    depends_on:
      - db
    links:
      - db